name: "MyAnimeList readme workflow"
author: "MoonLGH"
description: "Puts your newest activity from MyAnimeList into your readme"

inputs:
    username:
        description: "Your MAL user username"
        default: ""
        required: true

    gh_token:
        description: "GitHub access token with Repo scope"
        default: ${{ github.token }}
        required: true

    readme_path:
        description: "Path of the readme file you want to update"
        default: ""
        required: false

    branch:
        description: "Branch of the README.md"
        default: "main"
        required: false

runs:
    using: "composite"
    steps:
        - name: Install dep
          - uses: actions/setup-node@v2
            with:
              node-version: '14'
          - run: npm install
        - name: Running the script
          - run: node index.ts