name: "MyAnimeList readme workflow"
author: "MoonLGH"
description: "Puts your newest activity from MyAnimeList into your readme"

inputs:
    username:
        description: "Your MAL user username"
        default: ""
        required: true

    gh_token:
        description: "GitHub access token with Repo scope"
        default: ${{ github.token }}
        required: true

    readme_path:
        description: "Path of the readme file you want to update"
        default: ""
        required: false

    branch:
        description: "Branch of the README.md"
        default: "main"
        required: false
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v2
        - name: cloning MAL-autoreadme
          run: git clone https://github.com/MoonLGH/MAL-autoreadme.git
          shell: bash
        - name: Set Node.js 14
          uses: actions/setup-node@v2.4.1
          with:
               node-version: 14
        - name: Install dependencies
          working-directory: ./MAL-autoreadme
          run: npm i
          shell: bash
        - name: Run the script
          working-directory: ./MAL-autoreadme
          run: node index.js
          shell: bash